#!/usr/bin/env node
// Merge isolated work/slideXX artifacts into the renderer's shared inputs.
//
// Backward compatibility: this script is optional. Existing single-thread jobs can keep editing
// lib/slides.js and make_crops.py directly.
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const WORK_DIR = path.resolve(process.env.WORK_DIR || path.join(ROOT, 'work'));
const SLIDES_OUT = path.resolve(process.env.SLIDES_OUT || path.join(ROOT, 'lib', 'slides.js'));
const CROP_PLAN_OUT = path.resolve(process.env.CROP_PLAN_OUT || path.join(WORK_DIR, 'crop_plan.integrated.json'));
const REPORT_OUT = path.resolve(process.env.INTEGRATION_REPORT_OUT || path.join(WORK_DIR, 'integration_report.md'));

const PRELUDE = `// Auto-generated by integrate_parallel_work.js.
// Edit work/slideXX/*.fragment.js, then rerun the integrator.
const K = require('./kit');
const { C, bg, head, panel, T, badge, icon, banner, chevronBar, iconRows, detailRows, footer, crop } = K;
`;

function fail(message) {
  console.error(`integrate_parallel_work: ${message}`);
  process.exit(1);
}

function readJson(file) {
  try {
    return JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch (err) {
    fail(`cannot parse JSON ${path.relative(ROOT, file)}: ${err.message}`);
  }
}

function slideDirs() {
  if (!fs.existsSync(WORK_DIR)) fail(`missing work directory: ${WORK_DIR}`);
  return fs.readdirSync(WORK_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory() && /^slide\d+$/i.test(d.name))
    .map((d) => path.join(WORK_DIR, d.name))
    .sort((a, b) => {
      const na = Number(path.basename(a).match(/\d+/)[0]);
      const nb = Number(path.basename(b).match(/\d+/)[0]);
      return na - nb;
    });
}

function stripSharedScaffold(src) {
  return src
    .replace(/^\s*#!.*\r?\n/, '')
    .replace(/^\s*const\s+K\s*=\s*require\([^)]*kit[^)]*\);\s*$/mg, '')
    .replace(/^\s*const\s+\{[^}]*\}\s*=\s*K;\s*$/mg, '')
    .replace(/^\s*module\.exports\s*=\s*\{[^}]*\};?\s*$/mg, '')
    .trim();
}

function loadFragment(dir) {
  const files = fs.readdirSync(dir).filter((f) => /^s\d+\.fragment\.js$/i.test(f)).sort();
  if (files.length !== 1) {
    fail(`${path.relative(ROOT, dir)} must contain exactly one sN.fragment.js file; found ${files.length}`);
  }
  const file = path.join(dir, files[0]);
  const slideNo = Number(files[0].match(/^s(\d+)\.fragment\.js$/i)[1]);
  let src = stripSharedScaffold(fs.readFileSync(file, 'utf8'));
  const fn = `s${slideNo}`;
  const fnRegex = new RegExp(`\\bfunction\\s+${fn}\\s*\\(\\s*s\\s*\\)`);
  if (!fnRegex.test(src)) fail(`${path.relative(ROOT, file)} must define function ${fn}(s)`);
  if (/require\s*\(/.test(src)) {
    fail(`${path.relative(ROOT, file)} contains require(...). Fragments should use the shared kit prelude.`);
  }
  return { slideNo, fn, file, src };
}

function normalizeCrop(name, value, fallbackSlide) {
  let crop;
  if (Array.isArray(value)) {
    const [slide, x, y, w, h, edges = ''] = value;
    crop = { name, slide, x, y, w, h, feather_edges: edges };
  } else if (value && typeof value === 'object') {
    crop = { ...value, name: value.name || name };
  } else {
    fail(`invalid crop entry ${name}`);
  }
  if (crop.slide == null) crop.slide = fallbackSlide;
  crop.feather_edges = crop.feather_edges || crop.edges || crop.feather || '';
  for (const field of ['name', 'slide', 'x', 'y', 'w', 'h']) {
    if (crop[field] == null || crop[field] === '') fail(`crop ${crop.name || name} missing ${field}`);
  }
  for (const field of ['slide', 'x', 'y', 'w', 'h']) {
    crop[field] = Number(crop[field]);
    if (!Number.isFinite(crop[field])) fail(`crop ${crop.name} has non-numeric ${field}`);
  }
  crop.slide = Math.trunc(crop.slide);
  crop.feather_edges = String(crop.feather_edges).toUpperCase();
  if (!/^[LRTB]*$/.test(crop.feather_edges)) fail(`crop ${crop.name} has invalid feather_edges`);
  return crop;
}

function loadCropPlan(dir, slideNo) {
  const file = path.join(dir, 'crop_plan.json');
  if (!fs.existsSync(file)) return [];
  const data = readJson(file);
  const raw = Array.isArray(data) ? data : (Array.isArray(data.crops) ? data.crops : data.crops || data);
  if (Array.isArray(raw)) {
    return raw.map((entry) => normalizeCrop(entry.name, entry, slideNo));
  }
  return Object.entries(raw).map(([name, value]) => normalizeCrop(name, value, slideNo));
}

const dirs = slideDirs();
if (dirs.length === 0) fail(`no work/slideXX folders found in ${WORK_DIR}`);

const fragments = dirs.map(loadFragment).sort((a, b) => a.slideNo - b.slideNo);
const seenSlides = new Set();
for (const frag of fragments) {
  if (seenSlides.has(frag.slideNo)) fail(`duplicate slide fragment for s${frag.slideNo}`);
  seenSlides.add(frag.slideNo);
}

const cropNames = new Set();
const crops = [];
for (const frag of fragments) {
  for (const cropEntry of loadCropPlan(path.dirname(frag.file), frag.slideNo)) {
    if (cropNames.has(cropEntry.name)) fail(`duplicate crop name ${cropEntry.name}`);
    cropNames.add(cropEntry.name);
    crops.push(cropEntry);
  }
}

const slidesJs = [
  PRELUDE,
  ...fragments.map((f) => `// ------------------------------------------------------------ SLIDE ${f.slideNo}\n${f.src}`),
  `module.exports = { ${fragments.map((f) => f.fn).join(', ')} };\n`,
].join('\n\n');

fs.mkdirSync(path.dirname(SLIDES_OUT), { recursive: true });
fs.writeFileSync(SLIDES_OUT, slidesJs);

fs.mkdirSync(path.dirname(CROP_PLAN_OUT), { recursive: true });
fs.writeFileSync(CROP_PLAN_OUT, JSON.stringify({ crops }, null, 2) + '\n');

const required = [
  'measurements.json',
  'profile_override.json',
  'crop_plan.json',
  'reconstruction_notes.md',
  'editability_inventory.md',
];
const report = [];
report.push('# Parallel Worker Integration Report');
report.push('');
report.push(`work_dir: ${path.relative(ROOT, WORK_DIR) || '.'}`);
report.push(`slides_out: ${path.relative(ROOT, SLIDES_OUT)}`);
report.push(`crop_plan_out: ${path.relative(ROOT, CROP_PLAN_OUT)}`);
report.push('');
for (const frag of fragments) {
  const dir = path.dirname(frag.file);
  report.push(`## s${frag.slideNo}`);
  report.push(`fragment: ${path.relative(ROOT, frag.file)}`);
  for (const name of required) {
    report.push(`${name}: ${fs.existsSync(path.join(dir, name)) ? 'present' : 'missing'}`);
  }
  report.push('');
}
report.push(`merged_crops: ${crops.length}`);
report.push('');
report.push('Next commands:');
report.push('');
report.push('```bash');
report.push(`CROP_PLAN=${path.relative(ROOT, CROP_PLAN_OUT).replace(/\\/g, '/')} python make_crops.py`);
report.push('TARGET=both PPTX_OUT=out/deck.pptx HTML_OUT=out/deck.html node build.js');
report.push('```');
report.push('');

fs.writeFileSync(REPORT_OUT, report.join('\n'));

console.log(`wrote ${path.relative(ROOT, SLIDES_OUT)}`);
console.log(`wrote ${path.relative(ROOT, CROP_PLAN_OUT)} (${crops.length} crops)`);
console.log(`wrote ${path.relative(ROOT, REPORT_OUT)}`);
