#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

function usage() {
  console.log(`Merge slide-image-dual-render parallel worker fragments into lib/slides.js.

Usage:
  node scripts/merge_fragments.js [options]

Options:
  --work <path>      Work directory containing slideXX folders (default: work)
  --out <path>       Output slides file (default: lib/slides.js)
  --slides 1,2,3     Merge only selected slide numbers
  --dry-run          Print what would be merged without writing
  --backup           Back up an existing output before overwriting
  --help             Show this help
`);
}

function parseArgs(argv) {
  const opts = { work: 'work', out: path.join('lib', 'slides.js'), slides: null, dryRun: false, backup: false };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--help' || arg === '-h') opts.help = true;
    else if (arg === '--dry-run') opts.dryRun = true;
    else if (arg === '--backup') opts.backup = true;
    else if (arg === '--work') {
      if (!argv[i + 1]) throw new Error('--work requires a path');
      opts.work = argv[++i];
    } else if (arg === '--out') {
      if (!argv[i + 1]) throw new Error('--out requires a path');
      opts.out = argv[++i];
    } else if (arg === '--slides') {
      if (!argv[i + 1]) throw new Error('--slides requires a comma-separated list');
      opts.slides = new Set(argv[++i].split(',').map((s) => Number(s.trim())).filter(Boolean));
    } else {
      throw new Error(`unknown option: ${arg}`);
    }
  }
  return opts;
}

function fail(message) {
  throw new Error(message);
}

function stripComments(src) {
  return src
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/(^|[^:])\/\/.*$/gm, '$1');
}

function slideDirs(workDir, selected) {
  if (!fs.existsSync(workDir)) fail(`missing work directory: ${workDir}`);
  return fs.readdirSync(workDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && /^slide\d+$/i.test(entry.name))
    .map((entry) => {
      const n = Number(entry.name.match(/\d+/)[0]);
      return { n, dir: path.join(workDir, entry.name) };
    })
    .filter((entry) => !selected || selected.has(entry.n))
    .sort((a, b) => a.n - b.n);
}

function validateFragment(file, n) {
  const raw = fs.readFileSync(file, 'utf8').trim();
  const code = stripComments(raw);
  const fn = `s${n}`;
  const fnMatches = [...code.matchAll(/\bfunction\s+([A-Za-z_$][\w$]*)\s*\(\s*s\s*\)/g)].map((m) => m[1]);
  if (fnMatches.length !== 1 || fnMatches[0] !== fn) {
    fail(`${file} must define exactly one matching function ${fn}(s)`);
  }
  const forbidden = [
    [/require\s*\(/, 'require('],
    [/module\.exports/, 'module.exports'],
    [/\bexports\./, 'exports.'],
    [/\bTARGET\b/, 'TARGET'],
    [/\bmakePptxSurface\b/, 'makePptxSurface'],
    [/\bmakeHtmlSurface\b/, 'makeHtmlSurface'],
    [/\bpptx\b/i, 'pptx'],
    [/\bhtml\b/i, 'html'],
  ];
  for (const [rx, label] of forbidden) {
    if (rx.test(code)) fail(`${file} contains forbidden backend/shared logic: ${label}`);
  }
  return raw
    .replace(/^\s*const\s+K\s*=\s*require\([^)]*kit[^)]*\);\s*$/mg, '')
    .replace(/^\s*const\s+\{[^}]*\}\s*=\s*K;\s*$/mg, '')
    .replace(/^\s*module\.exports\s*=\s*\{[^}]*\};?\s*$/mg, '')
    .trim();
}

function findFragment(dir, n) {
  const expected = path.join(dir, `s${n}.fragment.js`);
  if (fs.existsSync(expected)) return expected;
  const matches = fs.readdirSync(dir).filter((name) => /^s\d+\.fragment\.js$/i.test(name));
  if (matches.length === 0) fail(`${dir} has no s${n}.fragment.js`);
  if (matches.length > 1) fail(`${dir} has multiple fragment files: ${matches.join(', ')}`);
  const only = matches[0];
  const foundN = Number(only.match(/^s(\d+)\.fragment\.js$/i)[1]);
  if (foundN !== n) fail(`${dir} contains ${only}, expected s${n}.fragment.js`);
  return path.join(dir, only);
}

function generatedSlides(fragments) {
  const names = fragments.map((f) => `s${f.n}`);
  return `// ============================================================
//  slides.js — GENERATED by scripts/merge_fragments.js
//  Source: work/slideXX/sN.fragment.js
//  Coordinates are SOURCE PIXELS. Do not branch on PPTX vs HTML.
//  Edit the fragments, then re-run the merger.
// ============================================================
const K = require('./kit');
const { C, bg, head, panel, T, badge, icon, banner, chevronBar, iconRows, detailRows, footer, crop } = K;

${fragments.map((f) => `// ------------------------------------------------------------ SLIDE ${f.n}\n${f.src}`).join('\n\n')}

module.exports = { ${names.join(', ')} };
`;
}

function main() {
  let opts;
  try {
    opts = parseArgs(process.argv.slice(2));
  } catch (err) {
    console.error(err.message);
    usage();
    process.exit(1);
  }
  if (opts.help) {
    usage();
    return;
  }

  const workDir = path.resolve(opts.work);
  const outFile = path.resolve(opts.out);
  const dirs = slideDirs(workDir, opts.slides);
  if (dirs.length === 0) fail(`no slideXX directories selected under ${workDir}`);

  const fragments = dirs.map(({ n, dir }) => {
    const file = findFragment(dir, n);
    return { n, file, src: validateFragment(file, n) };
  });

  console.log(`merge source: ${workDir}`);
  for (const f of fragments) console.log(`  s${f.n}: ${f.file}`);
  console.log(`merge output: ${outFile}`);

  if (opts.dryRun) {
    console.log('dry-run: no files written');
    return;
  }

  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  if (fs.existsSync(outFile) && opts.backup) {
    const backup = `${outFile}.bak_${new Date().toISOString().replace(/[-:.TZ]/g, '').slice(0, 14)}`;
    fs.copyFileSync(outFile, backup);
    console.log(`backup: ${backup}`);
  }
  fs.writeFileSync(outFile, generatedSlides(fragments), 'utf8');
  console.log(`wrote ${outFile}`);
}

try {
  main();
} catch (err) {
  console.error(`merge_fragments: ${err.message}`);
  process.exit(1);
}
